name: Deploy M-Motors

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: badreddine
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/m-motors

            git pull origin main

            docker compose down
            docker compose up -d --build